language: go
go:
  - 1.10.x
  - 1.11.x
before_install:
  - curl -L https://git.io/vp6lP | sh
  - mv bin $HOME/bin
  - go get -v golang.org/x/lint/golint
script:
  - "go build -o /dev/null ."
  - "$HOME/bin/gometalinter ."

